server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/finance
    username: root
    password: root123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    format_sql: true
##Setting logging levels
logging:
  level:
    org.hibernate.engine.spi.QueryParameters: TRACE
    org.hibernate.engine.query.spi.HQLQueryPlan: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE






